service:
  name: backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  profile: mrbartender
  stage: dev
  region: us-east-1
  memorySize: 512
  versionFunctions: false

functions:
  getRecipe:
    handler: src/recipe.get
    events:
      - http:
          method: get
          path: hello

resources:  # CloudFormation template syntax
  Resources:
    deviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: devices
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S
          - AttributeName: pour_code
            AttributeType: S
          - AttributeName: vendor
            AttributeType: N
        GlobalSecondaryIndexes:
          - IndexName: "GSI"
            KeySchema:
              - AttributeName: pour_code
                KeyType: "HASH"
              - AttributeName: vendor
                KeyType: "RANGE"
            Projection:
              ProjectionType: "KEYS_ONLY"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5      
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orders
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N 
          - AttributeName: consumer
            AttributeType: S
          - AttributeName: vendor
            AttributeType: N
          - AttributeName: device
            AttributeType: N    
        GlobalSecondaryIndexes:
          - IndexName: "GSI"
            KeySchema:
              - AttributeName: vendor
                KeyType: "HASH"
              - AttributeName: device
                KeyType: "RANGE"
            Projection:
              ProjectionType: "KEYS_ONLY"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5 
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: consumer
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    vendorsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: vendors
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S
          - AttributeName: semantic_id
            AttributeType: S
          - AttributeName: image
            AttributeType: S   
        GlobalSecondaryIndexes:
          - IndexName: "GSI"
            KeySchema:
              - AttributeName: semantic_id
                KeyType: "HASH"
              - AttributeName: image
                KeyType: "RANGE"
            Projection:
              ProjectionType: "KEYS_ONLY"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        KeySchema:
          - AttributeName: id
            KeyType: HASH 
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    categoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: categories
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S 
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    productTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S
          - AttributeName: proof
            AttributeType: N
          - AttributeName: ingredient
            AttributeType: N      
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: "GSI"
            KeySchema:
              - AttributeName: proof
                KeyType: "HASH"
              - AttributeName: ingredient
                KeyType: "RANGE"
            Projection:
              ProjectionType: "KEYS_ONLY"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ingredientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ingredients
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S 
          - AttributeName: alcoholic
            AttributeType: B 
        GlobalSecondaryIndexes:
          - IndexName: "GSI"
            KeySchema:
              - AttributeName: name
                KeyType: "HASH"
            Projection:
              ProjectionType: "KEYS_ONLY"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: alcoholic
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    recipesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: recipes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: status
            AttributeType: S
          - AttributeName: price
            AttributeType: N 
        GlobalSecondaryIndexes:
          - IndexName: "GSI"
            KeySchema:
              - AttributeName: price
                KeyType: "HASH"
            Projection:
              ProjectionType: "KEYS_ONLY"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5   
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: status
            KeyType: RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

